db {
  url = "jdbc:postgresql://localhost:5432/realestate"
  user = "realestate"
  password = "realestate"
  driver = "org.postgresql.Driver"
}

kafka {
  bootstrapServers = "localhost:9092"
  listingsTopic = "listings.events"
}
